const LinksItemData = [
  {
    id: 1,
    Heading: "Products",
    Item1: "Car insurance",
    Item2: "Third party bike insurance",
    Item3: "Two wheeler insurance",
    Item4: "Vehicle/Motor insurance",
    Item5: "Third party car insurance",
    Item6: "Health insurance",
    Item7: "Arogya sanjeevani policy",
    Item8: "Group health insurance for employees",
    // Item9: "",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 2,
    Heading: "Company",
    Item1: "About us",
    Item2: "Board of directors",
    Item3: "Careers",
    Item4: "Media kit",
    Item5: "All resources",
    Item6: "Articles",
    Item7: "Ackology - The tech blog",
    Item8: "Partnerships",
    Item9: "Sitemap",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 3,
    Heading: "Legal",
    Item1: "Whistleblower policy",
    Item2: "Public disclosure",
    Item3: "Financials & disclosures",
    Item4: "Privacy policy",
    Item5: "Terms & conditions",
    Item6: "Stewardship code",
    Item7: "Disclaimer",
    Item8: "Anti fraud policy",
    Item9: "Health underwriting philosophy",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 4,
    Heading: "Support",
    Item1: "Car insurance",
    Item2: "Contact us",
    Item3: "Customer service",
    Item4: "Cancellations & refunds",
    Item5: "Downloads",
    Item6: "Unclaimed amount",
    Item7: "IRDAI website",
    Item8: "Other products",
    // Item9: "",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 5,
    Heading: "Car Insurance",
    Item1: "Car insurance premium calculator",
    Item2: "Car insurance comparison",
    Item3: "Car insurance claim process",
    Item4: "IDV in car insurance",
    Item5: "Zero depreciation car insurance",
    Item6: "Brand new car insurance",
    Item7: "Electric car insurance",
    Item8: "Renew expired car insurance online",
    Item9: "Old car insurance",
    Item10: "Car insurance articles",
    Item11: "Car insurance guides",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 6,
    Heading: "Bike insurance",
    Item1: " Bike insurance premium calculator",
    Item2: "Compare two wheeler insurance online",
    Item3: "Bike/Two wheeler insurance claim process ",
    Item4: "IDV in bike insurance",
    Item5: "Own damage insurance for bike",
    Item6: "New bike insurance",
    Item7: "Scooter insurance",
    Item8: "Old bike insurance",
    Item9: "Electric bike insurance",
    Item10: "Bike insurance articles",
    Item11: "Bike insurance guides",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 7,
    Heading: "Health insurance",
    Item1: "Health insurance premium calculator",
    Item2: "Compare health insurance",
    Item3: "Health insurance claim",
    Item4: "Cashless health insurance",
    Item5: "Renewing mediclaim policy online",
    Item6: "Individual mediclaim policy",
    Item7: "COVID-19 health insurance",
    Item8: "Corona kavach policy",
    Item9: "1 crore health insurance",
    Item10: "Health insurance articles",
    Item11: "Health insurance guides",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 8,
    Heading: "Explore car insurance",
    Item1: "Own damage insurance",
    Item2: "SUV car insurance",
    Item3: "Add-on cover in car insurance",
    Item4: "Car theft insurance",
    Item5: "Cashless garages for vehicle insurance",
    Item6: "Tyre protection in car insurance",
    Item7: "Commercial vehicle insurance",
    Item8: "Car insurance claim settlement ratio",
    Item9: "Car insurance in Bangalore",
    Item10: "Car insurance in Hyderabad",
    Item11: "Car insurance in Chennai",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 9,
    Heading: "Explore bike insurance",
    Item1: "Bike insurance claim settlement ratio",
    Item2: "Comprehensive vs third party bike insurance",
    Item3: "What is NCB in bike insurance?",
    Item4: "First party bike insurance",
    Item5: "Personal accident cover in bike insurance",
    Item6: "Two wheeler insurance renewal online after expiry",
    Item7: "Constructive total loss in bike insurance",
    Item8: "Insurance for rental bikes",
    Item9: "Duplicate bike insurance copy online",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 10,
    Heading: "Explore health insurance",
    Item1: "Waiting period in health insurance",
    Item2: "Reimbursement health insurance",
    Item3: "Women's health insurance",
    Item4: "Health insurance for parents",
    Item5: "Health insurance for children",
    Item6: "Health insurance for senior citizens",
    Item7: "Health insurance plans for family",
    Item8: "Types of health insurance",
    Item9: "Health insurance portability",
    Item10: "Preventive health check-up",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 11,
    Heading: "Explore group health insurance",
    Item1: "Corporate health Insurance",
    Item2: "Group health insurance add-ons",
    Item3: "Maternity cover in group health insurance",
    Item4: "Daily hospital cash benefit in group health insurance",
    Item5: "Group health insurance for pre-existing diseases",
    Item6: "Tax benefits of group health insurance",
    Item7: "Corporate health insurance when changing jobs",
    Item8: "Group health insurance eligibility requirements",
    Item9: "How are group health insurance premiums calculated?",
    Item10: "Startup health insurance",
    Item11: "Group health insurance",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 12,
    Heading: "Explore more",
    Item1: "RTO Office",
    Item2: "Traffic Rules and Fines",
    Item2: "PUC Certificate",
    Item3: "Vehicle Fitness Certificate",
    Item4: "New Vehicle Registration",
    Item5: "Vehicle Owner details by Number Plate",
    Item6: "Claim Settlement Ratio",
    Item7: "Types of Insurance",
    Item8: "Fuel Prices Today",
    Item9: "Petrol Prices in India",
    Item10: "Diesel Prices in India",
    Item11: "UAN",
 
  },
  {
    id: 13,
    Heading: "Explore travel insurance",
    Item1: "Travel Insurance",
    Item2: "International Travel Insurance",
    Item3: "USA Travel Insurance",
    Item4: "Schengen Travel Insurance",
    Item5: "Travel Insurance for Dubai",
    Item6: "Travel Insurance for Thailand",
    Item7: "Is Travel Insurance mandatory?",
    // Item8: " ",
    // Item9: "",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
  {
    id: 14,
    Heading: "Explore life insurance",
    Item1: "Life Insurance",
    Item2: "Term Insurance",
    Item3: "Types of Life Insurance",
    Item4: "Life Insurance Riders",
    // Item5: " ",
    // Item6: " ",
    // Item7: " ",
    // Item8: " ",
    // Item9: "",
    // Item10: "",
    // Item11: "",
    // Item12: "",
    // Item13: "",
    // Item14: "",
    // Item15: "",
  },
];


export default LinksItemData;



// export const Products = [
//   {
//         Item1: "Car insurance",
        
//   },




// ];